//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.08 at 03:37:41 PM MESZ 
//


package com.catify.core.process.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fork complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fork">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.catify.com/api/1.0}SplitNode">
 *       &lt;attribute ref="{http://www.catify.com/api/1.0}receivingLines"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fork")
public class Fork
    extends SplitNode
{

    @XmlAttribute(namespace = "http://www.catify.com/api/1.0")
    protected Integer receivingLines;

    /**
     * Gets the value of the receivingLines property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getReceivingLines() {
        if (receivingLines == null) {
            return -1;
        } else {
            return receivingLines;
        }
    }

    /**
     * Sets the value of the receivingLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReceivingLines(Integer value) {
        this.receivingLines = value;
    }

}
