//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.03 at 02:15:23 PM MEZ 
//


package com.catify.core.process.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Group complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Group">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.catify.com/api/1.0}StructureNode">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.catify.com/api/1.0}events" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Group", propOrder = {
    "messageEvent",
    "timeEvent",
    "exceptionEvent"
})
public class Group
    extends StructureNode
{

    protected List<MessageEvent> messageEvent;
    protected TimeEvent timeEvent;
    protected List<ExceptionEvent> exceptionEvent;

    /**
     * Gets the value of the messageEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageEvent }
     * 
     * 
     */
    public List<MessageEvent> getMessageEvent() {
        if (messageEvent == null) {
            messageEvent = new ArrayList<MessageEvent>();
        }
        return this.messageEvent;
    }

    /**
     * Gets the value of the timeEvent property.
     * 
     * @return
     *     possible object is
     *     {@link TimeEvent }
     *     
     */
    public TimeEvent getTimeEvent() {
        return timeEvent;
    }

    /**
     * Sets the value of the timeEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeEvent }
     *     
     */
    public void setTimeEvent(TimeEvent value) {
        this.timeEvent = value;
    }

    /**
     * Gets the value of the exceptionEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exceptionEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExceptionEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExceptionEvent }
     * 
     * 
     */
    public List<ExceptionEvent> getExceptionEvent() {
        if (exceptionEvent == null) {
            exceptionEvent = new ArrayList<ExceptionEvent>();
        }
        return this.exceptionEvent;
    }

}
