package com.catify.tester

import com.catify.types.Decision

declare Payload
	value : int
end

declare class_cfd7332952eff5ecdbfba16124067d70
	payload : Payload
end
	
rule "to-02f7c32af3d977dcddcbcd77cf7500ff"
dialect "mvel"
when
	//value equals 10
	$p: class_cfd7332952eff5ecdbfba16124067d70( payload.value == 10 )
	$d: Decision( )
then
	//goto node 02f7c32af3d977dcddcbcd77cf7500ff
	modify( $d ) { result = "node-02f7c32af3d977dcddcbcd77cf7500ff" }
	retract( $p )
end
	
rule "to-c5f00e5f3462795fdc4ccc98b4bbb818"
dialect "mvel"
when
	//value equals 20
	$p: class_cfd7332952eff5ecdbfba16124067d70( payload.value == 20 )
	$d: Decision( )
then
	//goto node c5f00e5f3462795fdc4ccc98b4bbb818
	modify( $d ) { result = "node-c5f00e5f3462795fdc4ccc98b4bbb818" }
	retract( $p )
end
	
rule "to-98fc2186952c29fd4ee8749b036c5eee"
dialect "mvel"
when
	//value equals 30
	$p: class_cfd7332952eff5ecdbfba16124067d70( payload.value == 30 )
	$d: Decision( )
then
	//goto node 98fc2186952c29fd4ee8749b036c5eee
	modify( $d ) { result = "node-98fc2186952c29fd4ee8749b036c5eee" }
	retract( $p )
end