//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.11 at 02:55:39 PM MEZ 
//


package com.catify.core.process.xml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.catify.core.process.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Group_QNAME = new QName("http://www.catify.com/api/1.0", "group");
    private final static QName _Receive_QNAME = new QName("http://www.catify.com/api/1.0", "receive");
    private final static QName _Variable_QNAME = new QName("http://www.catify.com/api/1.0", "variable");
    private final static QName _End_QNAME = new QName("http://www.catify.com/api/1.0", "end");
    private final static QName _Reply_QNAME = new QName("http://www.catify.com/api/1.0", "reply");
    private final static QName _Start_QNAME = new QName("http://www.catify.com/api/1.0", "start");
    private final static QName _TimeEvent_QNAME = new QName("http://www.catify.com/api/1.0", "timeEvent");
    private final static QName _Request_QNAME = new QName("http://www.catify.com/api/1.0", "request");
    private final static QName _PipelineExceptionEvent_QNAME = new QName("http://www.catify.com/api/1.0", "pipelineExceptionEvent");
    private final static QName _Process_QNAME = new QName("http://www.catify.com/api/1.0", "process");
    private final static QName _Sleep_QNAME = new QName("http://www.catify.com/api/1.0", "sleep");
    private final static QName _Decision_QNAME = new QName("http://www.catify.com/api/1.0", "decision");
    private final static QName _ExceptionEvent_QNAME = new QName("http://www.catify.com/api/1.0", "exceptionEvent");
    private final static QName _Endpoint_QNAME = new QName("http://www.catify.com/api/1.0", "endpoint");
    private final static QName _Variables_QNAME = new QName("http://www.catify.com/api/1.0", "variables");
    private final static QName _Xpath_QNAME = new QName("http://www.catify.com/api/1.0", "xpath");
    private final static QName _InPipeline_QNAME = new QName("http://www.catify.com/api/1.0", "inPipeline");
    private final static QName _Line_QNAME = new QName("http://www.catify.com/api/1.0", "line");
    private final static QName _Correlation_QNAME = new QName("http://www.catify.com/api/1.0", "correlation");
    private final static QName _MessageEvent_QNAME = new QName("http://www.catify.com/api/1.0", "messageEvent");
    private final static QName _OutPipeline_QNAME = new QName("http://www.catify.com/api/1.0", "outPipeline");
    private final static QName _Terminate_QNAME = new QName("http://www.catify.com/api/1.0", "terminate");
    private final static QName _Fork_QNAME = new QName("http://www.catify.com/api/1.0", "fork");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.catify.core.process.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Fork }
     * 
     */
    public Fork createFork() {
        return new Fork();
    }

    /**
     * Create an instance of {@link Pipeline }
     * 
     */
    public Pipeline createPipeline() {
        return new Pipeline();
    }

    /**
     * Create an instance of {@link Variables }
     * 
     */
    public Variables createVariables() {
        return new Variables();
    }

    /**
     * Create an instance of {@link StructureNode }
     * 
     */
    public StructureNode createStructureNode() {
        return new StructureNode();
    }

    /**
     * Create an instance of {@link SplitNode }
     * 
     */
    public SplitNode createSplitNode() {
        return new SplitNode();
    }

    /**
     * Create an instance of {@link Endpoint }
     * 
     */
    public Endpoint createEndpoint() {
        return new Endpoint();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link ServiceNode }
     * 
     */
    public ServiceNode createServiceNode() {
        return new ServiceNode();
    }

    /**
     * Create an instance of {@link Correlation }
     * 
     */
    public Correlation createCorrelation() {
        return new Correlation();
    }

    /**
     * Create an instance of {@link Start }
     * 
     */
    public Start createStart() {
        return new Start();
    }

    /**
     * Create an instance of {@link Decision }
     * 
     */
    public Decision createDecision() {
        return new Decision();
    }

    /**
     * Create an instance of {@link Sleep }
     * 
     */
    public Sleep createSleep() {
        return new Sleep();
    }

    /**
     * Create an instance of {@link Reply }
     * 
     */
    public Reply createReply() {
        return new Reply();
    }

    /**
     * Create an instance of {@link InPipeline }
     * 
     */
    public InPipeline createInPipeline() {
        return new InPipeline();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

    /**
     * Create an instance of {@link Terminate }
     * 
     */
    public Terminate createTerminate() {
        return new Terminate();
    }

    /**
     * Create an instance of {@link OutPipeline }
     * 
     */
    public OutPipeline createOutPipeline() {
        return new OutPipeline();
    }

    /**
     * Create an instance of {@link MessageEvent }
     * 
     */
    public MessageEvent createMessageEvent() {
        return new MessageEvent();
    }

    /**
     * Create an instance of {@link Receive }
     * 
     */
    public Receive createReceive() {
        return new Receive();
    }

    /**
     * Create an instance of {@link TimeEvent }
     * 
     */
    public TimeEvent createTimeEvent() {
        return new TimeEvent();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link PipelineExceptionEvent }
     * 
     */
    public PipelineExceptionEvent createPipelineExceptionEvent() {
        return new PipelineExceptionEvent();
    }

    /**
     * Create an instance of {@link ExceptionEvent }
     * 
     */
    public ExceptionEvent createExceptionEvent() {
        return new ExceptionEvent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "group")
    public JAXBElement<Group> createGroup(Group value) {
        return new JAXBElement<Group>(_Group_QNAME, Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Receive }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "receive")
    public JAXBElement<Receive> createReceive(Receive value) {
        return new JAXBElement<Receive>(_Receive_QNAME, Receive.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Variable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "variable")
    public JAXBElement<Variable> createVariable(Variable value) {
        return new JAXBElement<Variable>(_Variable_QNAME, Variable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link End }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "end")
    public JAXBElement<End> createEnd(End value) {
        return new JAXBElement<End>(_End_QNAME, End.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "reply")
    public JAXBElement<Reply> createReply(Reply value) {
        return new JAXBElement<Reply>(_Reply_QNAME, Reply.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Start }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "start")
    public JAXBElement<Start> createStart(Start value) {
        return new JAXBElement<Start>(_Start_QNAME, Start.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "timeEvent")
    public JAXBElement<TimeEvent> createTimeEvent(TimeEvent value) {
        return new JAXBElement<TimeEvent>(_TimeEvent_QNAME, TimeEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "request")
    public JAXBElement<Request> createRequest(Request value) {
        return new JAXBElement<Request>(_Request_QNAME, Request.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PipelineExceptionEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "pipelineExceptionEvent")
    public JAXBElement<PipelineExceptionEvent> createPipelineExceptionEvent(PipelineExceptionEvent value) {
        return new JAXBElement<PipelineExceptionEvent>(_PipelineExceptionEvent_QNAME, PipelineExceptionEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "process")
    public JAXBElement<Process> createProcess(Process value) {
        return new JAXBElement<Process>(_Process_QNAME, Process.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sleep }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "sleep")
    public JAXBElement<Sleep> createSleep(Sleep value) {
        return new JAXBElement<Sleep>(_Sleep_QNAME, Sleep.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Decision }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "decision")
    public JAXBElement<Decision> createDecision(Decision value) {
        return new JAXBElement<Decision>(_Decision_QNAME, Decision.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExceptionEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "exceptionEvent")
    public JAXBElement<ExceptionEvent> createExceptionEvent(ExceptionEvent value) {
        return new JAXBElement<ExceptionEvent>(_ExceptionEvent_QNAME, ExceptionEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Endpoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "endpoint")
    public JAXBElement<Endpoint> createEndpoint(Endpoint value) {
        return new JAXBElement<Endpoint>(_Endpoint_QNAME, Endpoint.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Variables }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "variables")
    public JAXBElement<Variables> createVariables(Variables value) {
        return new JAXBElement<Variables>(_Variables_QNAME, Variables.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "xpath")
    public JAXBElement<String> createXpath(String value) {
        return new JAXBElement<String>(_Xpath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InPipeline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "inPipeline")
    public JAXBElement<InPipeline> createInPipeline(InPipeline value) {
        return new JAXBElement<InPipeline>(_InPipeline_QNAME, InPipeline.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Line }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "line")
    public JAXBElement<Line> createLine(Line value) {
        return new JAXBElement<Line>(_Line_QNAME, Line.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Correlation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "correlation")
    public JAXBElement<Correlation> createCorrelation(Correlation value) {
        return new JAXBElement<Correlation>(_Correlation_QNAME, Correlation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "messageEvent")
    public JAXBElement<MessageEvent> createMessageEvent(MessageEvent value) {
        return new JAXBElement<MessageEvent>(_MessageEvent_QNAME, MessageEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutPipeline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "outPipeline")
    public JAXBElement<OutPipeline> createOutPipeline(OutPipeline value) {
        return new JAXBElement<OutPipeline>(_OutPipeline_QNAME, OutPipeline.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Terminate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "terminate")
    public JAXBElement<Terminate> createTerminate(Terminate value) {
        return new JAXBElement<Terminate>(_Terminate_QNAME, Terminate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fork }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.catify.com/api/1.0", name = "fork")
    public JAXBElement<Fork> createFork(Fork value) {
        return new JAXBElement<Fork>(_Fork_QNAME, Fork.class, null, value);
    }

}
