//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.13 at 06:05:33 PM MESZ 
//


package com.catify.core.process.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Process complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Process">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.catify.com/api/1.0}start"/>
 *         &lt;group ref="{http://www.catify.com/api/1.0}events" minOccurs="0"/>
 *         &lt;group ref="{http://www.catify.com/api/1.0}nodes" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="accountName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="processName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="processVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="processId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Process", propOrder = {
    "start",
    "messageEvent",
    "timeEvent",
    "exceptionEvent",
    "nodes"
})
public class Process {

    @XmlElement(required = true)
    protected Start start;
    protected List<MessageEvent> messageEvent;
    protected TimeEvent timeEvent;
    protected List<ExceptionEvent> exceptionEvent;
    @XmlElements({
        @XmlElement(name = "receive", type = Receive.class),
        @XmlElement(name = "fork", type = Fork.class),
        @XmlElement(name = "end", type = End.class),
        @XmlElement(name = "reply", type = Reply.class),
        @XmlElement(name = "decision", type = Decision.class),
        @XmlElement(name = "group", type = Group.class),
        @XmlElement(name = "terminate", type = Terminate.class),
        @XmlElement(name = "sleep", type = Sleep.class),
        @XmlElement(name = "request", type = Request.class)
    })
    protected List<Node> nodes;
    @XmlAttribute(required = true)
    protected String accountName;
    @XmlAttribute(required = true)
    protected String processName;
    @XmlAttribute(required = true)
    protected String processVersion;
    @XmlAttribute
    protected String processId;

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link Start }
     *     
     */
    public Start getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link Start }
     *     
     */
    public void setStart(Start value) {
        this.start = value;
    }

    /**
     * Gets the value of the messageEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageEvent }
     * 
     * 
     */
    public List<MessageEvent> getMessageEvent() {
        if (messageEvent == null) {
            messageEvent = new ArrayList<MessageEvent>();
        }
        return this.messageEvent;
    }

    /**
     * Gets the value of the timeEvent property.
     * 
     * @return
     *     possible object is
     *     {@link TimeEvent }
     *     
     */
    public TimeEvent getTimeEvent() {
        return timeEvent;
    }

    /**
     * Sets the value of the timeEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeEvent }
     *     
     */
    public void setTimeEvent(TimeEvent value) {
        this.timeEvent = value;
    }

    /**
     * Gets the value of the exceptionEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exceptionEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExceptionEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExceptionEvent }
     * 
     * 
     */
    public List<ExceptionEvent> getExceptionEvent() {
        if (exceptionEvent == null) {
            exceptionEvent = new ArrayList<ExceptionEvent>();
        }
        return this.exceptionEvent;
    }

    /**
     * Gets the value of the nodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Receive }
     * {@link Fork }
     * {@link End }
     * {@link Reply }
     * {@link Decision }
     * {@link Group }
     * {@link Terminate }
     * {@link Sleep }
     * {@link Request }
     * 
     * 
     */
    public List<Node> getNodes() {
        if (nodes == null) {
            nodes = new ArrayList<Node>();
        }
        return this.nodes;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the processName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * Sets the value of the processName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessName(String value) {
        this.processName = value;
    }

    /**
     * Gets the value of the processVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessVersion() {
        return processVersion;
    }

    /**
     * Sets the value of the processVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessVersion(String value) {
        this.processVersion = value;
    }

    /**
     * Gets the value of the processId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * Sets the value of the processId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessId(String value) {
        this.processId = value;
    }

}
